services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: stripe
      POSTGRES_PASSWORD: stripe
      POSTGRES_DB: stripe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    env_file: .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
